### PR TITLE
Use textarea type for reason and comment fields

### PR DESCRIPTION
**Pull request by Universal-Omega**
This has been mentioned multiple times so doing this. It also adds a help message to the reason field.

Also makes it so you can't post an empty comment or open a wiki request with a completely empty reason (or contains only whitespace or newlines)

### CODE REVIEW

**Comment by dmehus** [comment]
Yeah, I think I've even suggested this in the past year (last fall sometime, as I recall). I'd suggest a 3-4 line text area field. How many lines have you proposed with https://github.com/miraheze/CreateWiki/pull/215/commits/fe11a70d7ccf6f23d331f229d704936dc325f6ac? No concerns otherwise, so 👍

**Comment by Universal-Omega** [comment]
> Yeah, I think I've even suggested this in the past year (last fall sometime, as I recall). I'd suggest a 3-4 line text area field. How many lines have you proposed with [fe11a70](https://github.com/miraheze/CreateWiki/commit/fe11a70d7ccf6f23d331f229d704936dc325f6ac)? No concerns otherwise, so 👍

Default is 25 rows, I just fixed it to be a 6 row field

**Comment by dmehus** [comment]
I think @Universal-Omega changed it to 4 rows per discussion on IRC, so LGTM and 👍 per that. Feel free to do the `i18n` messages; if any changes, I can always modify them after

**Review by dmehus — APPROVED** [review]
This seems fine, and you used the correct `you're`, so 👍

**Pull request merged**
