### PR TITLE
convert private to a checkbox

### PR DESCRIPTION
**Pull request by The-Voidwalker**
not too sure of the logic on line 128 tho

### CODE REVIEW

**Comment by paladox** [comment]
cc @JohnFLewis  :)

**Comment by JohnFLewis** [comment]
It was meant to be a checkbox. c&ping fun

**Comment by paladox** [comment]
@JohnFLewis should i merge?

**Comment by JohnFLewis** [comment]
It’s meant to be it so yes.

**Comment by paladox** [comment]
ok, thanks, done.

Deployed with "salt -E 'mw.*' cmd.run "puppet agent -tv""

**Pull request merged**
