### PR TITLE
Added Phabricator and Discord Links to default mainpage; changed external link style to interwiki format

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by dmehus** [comment]
Not opposed to this, but is there any reason why you've linked to https://discord.is/Miraheze_Discord, which is a web redirect to  https://robyul.chat, @Universal-Omega? I think the link should be either to (a) the Miraheze Discord server itself or (b) https://meta.miraheze.org/wiki/Discord.

**Comment by Universal-Omega** [comment]
@dmehus I didn't link to https://discord.is/Miraheze_Discord, I linked to https://discord.is/Miraheze which is a redirect to a join for the server

**Comment by dmehus** [comment]
> @dmehus I didn't link to https://discord.is/Miraheze_Discord, I linked to https://discord.is/Miraheze which is a redirect to a join for the server

@Universal-Omega Okay, I see that now. It's just weird that that "discord.is/Miraheze_Discord" links to robyul's bot website, versus "Miraheze" which links to us. Carry on.

**Comment by RhinosF1** [comment]
@dmheus: discord.is is provided by robyul.chat

/miraheze is a valid link

Instead of a 404, it sends you to their homepage for invalid ones.

**Review by RhinosF1 — APPROVED** [review]
Don't see an issue. @JohnFLewis: mind deploying this with your next set of changes?

**Comment by Universal-Omega** [comment]
redone in #176

**Pull request closed without merging**
