### PR TITLE
Remove unneeded comments where it only says param or return types

### PR DESCRIPTION
**Pull request by Universal-Omega**
Type hints tell you this so the docs are unnecessary if they don't explain anything else.

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
These aren't unneeded. They are used for doc generation and it's mediawiki standard to include them.

**Comment by Universal-Omega** [comment]
> These aren't unneeded. They are used for doc generation and it's mediawiki standard to include them.

Not anymore it seems.
https://phabricator.wikimedia.org/T258925

and https://phabricator.wikimedia.org/T343443 for example

**Comment by RhinosF1** [comment]
That surprises me, the coding style documentation makes no reference to it and I wonder how much it's followed.

**Comment by RhinosF1** [comment]
We should on the same notes probably actually attempt to generate docs and publish them somewhere for our maintained extensions.

**Comment by Universal-Omega** [comment]
Hmm maybe we should keep these documentation and instead expensively document everything with more explanation which would also solve the redundancy.

**Pull request closed without merging**
