### PR TITLE
Allow $wgCreateWikiBlacklistedSubdomains to be an array

### PR DESCRIPTION
**Pull request by Universal-Omega**
So it's easier to add new regex blacklists, and doesn't have one huge string. Feel free to close this if it isn't a good idea to do though.

### CODE REVIEW

**Comment by dmehus** [comment]
@Universal-Omega Was this variable currently a string, and this PR proposes to convert it to an array? If _so_, this seems to make a lot of sense, and simplifies the list of blacklisted CreateWiki subdomains, I think

**Comment by Universal-Omega** [comment]
> @Universal-Omega Was this variable currently a string, and this PR proposes to convert it to an array? If _so_, this seems to make a lot of sense, and simplifies the list of blacklisted CreateWiki subdomains, I think

Yes, it's currently a string, this PR allows it to continue being a string, but also supports it being an array, for simplicity and making it not be just a huge string.

**Comment by dmehus** [comment]
> > @Universal-Omega Was this variable currently a string, and this PR proposes to convert it to an array? If _so_, this seems to make a lot of sense, and simplifies the list of blacklisted CreateWiki subdomains, I think
> 
> Yes, it's currently a string, this PR allows it to continue being a string, but also supports it being an array, for simplicity and making it not be just a huge string.

Oh, gotcha. It simplifies the string then? Well I definitely support moving it to an array.

**Comment by Universal-Omega** [comment]
> > > @Universal-Omega Was this variable currently a string, and this PR proposes to convert it to an array? If _so_, this seems to make a lot of sense, and simplifies the list of blacklisted CreateWiki subdomains, I think
> > 
> > 
> > Yes, it's currently a string, this PR allows it to continue being a string, but also supports it being an array, for simplicity and making it not be just a huge string.
> 
> Oh, gotcha. It simplifies the string then? Well I definitely support moving it to an array.

No it doesn't simplify string, it simplifies config by supporting it as an array. But maintains compatibility with the former string.

**Comment by dmehus** [comment]
> > > > @Universal-Omega Was this variable currently a string, and this PR proposes to convert it to an array? If _so_, this seems to make a lot of sense, and simplifies the list of blacklisted CreateWiki subdomains, I think
> > > 
> > > 
> > > Yes, it's currently a string, this PR allows it to continue being a string, but also supports it being an array, for simplicity and making it not be just a huge string.
> > 
> > 
> > Oh, gotcha. It simplifies the string then? Well I definitely support moving it to an array.
> 
> No it doesn't simplify string, it simplifies config by supporting it as an array. But maintains compatibility with the former string.

Okay, thanks for clarifying.

**Pull request merged**
